### ISSUE TITLE
Connection Problem with Signaling server

### ISSUE THREAD

**Issue by markkhanippbx** [strukturag/nextcloud-spreed-signaling#321] opened 2022-08-12 22:39 UTC
Hi I'm using Nextcloud 23. After updating I installed a fresh signaling server using following steps. 

https://morph027.gitlab.io/blog/nextcloud-spreed-signaling/ 

Now all is fine on server end it is connecting with NC23 with url and key. But when joining the call error comes on both ends saying connection problem. 

![image](https://user-images.githubusercontent.com/55556923/184453365-f510ad94-53f4-4a98-a24e-3ee6d7115bdf.png)

Janus server is updated and running.

**Comment by zohaib09** [comment] 2022-08-13 16:34
I have the same issue. I had also posted here but didn't get solution. please someone advise here.

**Comment by muchahagrande** [comment] 2022-08-26 16:21
Did you tried with different browsers?

**Comment by fancycode** [comment] 2022-08-30 08:16
Please check `chrome://webrtc-internals` for problems. Are your users behind a firewall / proxy / NAT and did you configure a STUN and TURN server? Most likely this is related to the clients not being able to connect to the Janus WebRTC gateway.

**Comment by fancycode** [comment] 2023-01-17 12:41
The signaling server does not transmit audio/video, so I doubt that the problem is related to the signaling server. Most likely there is a problem with the Janus / STUN / TURN setup where as a result some clients can't connect to the Janus gateway.

Debugging such connectivity issues is out of scope for the signaling server, please open a issue at the Nextcloud community support for Talk at https://help.nextcloud.com/c/support/talk/52.

**Closed by fancycode** 2023-01-17 12:41 UTC
