### ISSUE TITLE
Video room is not switching to the person that speaks. 

### ISSUE THREAD

**Issue by ChrisEKN** [strukturag/nextcloud-spreed-signaling#24] opened 2020-06-15 12:53 UTC
**Bug.**
When we connect the spreed-signaling server it no longer switch automatically to the person that speaks during the video conference. It will pick a random main webcam feed that will always stay the main webcam feed. The main webcam feed is different for each person that is connected to that meeting. So it randomly pics a webcam feed for each person that is connected.

**Expected behaviour:** 
The default talk app when you create a video conference with 3 or more people, it will select the person that speaks as the main webcam feed.

**Comment by fancycode** [comment] 2020-06-30 14:38
@danxuliu this sounds like a frontend issue, should this go to the Talk repository?

**Comment by Chartman123** [comment] 2020-07-05 11:31
Probably, yes.

**Comment by derryaire** [comment] 2020-07-06 06:45
I'm not so sure about that. The moment I stop using the signaling server, Nextcloud Talk is following the speaker again.

**Comment by danxuliu** [comment] 2020-07-06 08:42
Switching to the speaker is done based on the received data channel messages (we need to get rid of that, but... some day :-P ), which are managed by Janus. Currently _nextcloud-spreed-signaling_ works better when used with Janus 0.4.3, are you using that version? If not, could you try with that version? Thanks.

Also note that data channels are not supported in Edge, so switching the speaker does not work in that browser, although that does not seem to be the case here.

**Comment by derryaire** [comment] 2020-07-08 10:23
Sorry, I already upgraded to Ubuntu 20.04 and used Morph027's repository (https://gitlab.com/packaging/janus/) to upgrade Janus to 0.10.2. It's currently productive and I don't want to mess around with it.
When I have some time to spare I'll set up another server with Ubuntu 18.04 as I've seen a PPA (Joachim Bauch) with Janus 0.4.3.

**Comment by derryaire** [comment] 2020-07-12 13:25
I've set up another VM with Ubuntu 18.04 and Janus 0.4.3 from Joachim Bauch's PPA. It works as intended and switches to the active speaker correctly.

**Comment by fancycode** [comment] 2020-07-14 09:03
Is the Janus you are using built with support for data channels? The one from my PPA is.

Closing as not related to the signaling server but a problem with the Janus setup.

**Closed by fancycode** 2020-07-14 09:03 UTC

**Comment by fancycode** [comment] 2020-07-30 13:26
You can follow https://github.com/nextcloud/spreed/issues/3937 for changes in Nextcloud Talk to better support newer versions of Janus.
