### ISSUE TITLE
Connect this stack with a multi domain Nextcloud Instance

### ISSUE THREAD

**Issue by cari-coders** [strukturag/nextcloud-spreed-signaling#862] opened 2024-11-08 17:44 UTC
Hey there!

First of all, thanks for the amazing dockerized version of the signaling services. It makes things a lot easier! However, I am stuck configuring the services in order to make them work with differnet domains.

Situation: I am running a dockerized nextcloud that is used by different groups with different domains (lets say nextcloud.domain1.com and nextcloud.domain2.com). At first, I have set up the services from this repo by using the ubuntu_install_nextcloud_signal.sh script (which, again, is really amazing). I used signal.domain1.com as domain during the configuration process.

When I am accessing my nextcloud talk app via nextcloud.domain1.com the hpb and all other related services work without problems. However, when i am accessing my nextcloud through nextcloud.domain2.com, I get the error "Failed to establish signaling connection. Something might be wrong in the signaling server configuration".

I am experienced with docker and linux, but i couldn't yet establish a proper understanding of the services in this repo. So my first trials were not entirely successfull:

1. I added another [backend] to the server.conf of the signaling server which contains the second domain as url. Interestingly, that enabled me to text and open calls with the nextcloud talk app through nextcloud.domain2.com, but no video and no sound was transmitted and the call broke down after a couple of seconds every time i tried.

2. I didn't find a way to add another "Realm" to the coturn container. So i added another coturn service to the docker compose file and set its realm to domain2.com. I configured the second coturn service to listen on port 3479. In the nextcloud talk settings, i added another stun and turn instance which pointed to the second port. So inside my nextcloud talk settings, i had two stun services and two turn services defined. However, the problem remaind.

I stopped now trying to find a solution since I noticed that I am missing information and knowledge about which services must be configured differently in order to make the multi domain setting working. I would be very thankful to receive some guidance or maybe even a solution for this problem.

I might add that I am sure that the domain configuration and ssl certificates are fine. In fact, with the first domain I can use all Nextcloud Talk features without problems. 

Thanks in Advance and thanks again for your amazing work!
Lux - CariCoders

**Comment by fancycode** [comment] 2024-11-11 10:51
Duplicate of #347 

I don't know about the `ubuntu_install_nextcloud_signal.sh` script (not part of this repository).

The problem most likely is that the second backend you added with the other domain is independent from the first one and Nextcloud will internally (through cron or others code paths) send requests to the signaling server for the first backend.

**Closed by fancycode** 2024-11-11 10:51 UTC
