### ISSUE TITLE
Fail connection with signaling"context deadline exceeded" or 'parse error: expected { near offset 1 of '' '

### ISSUE THREAD

**Issue by willyamcts** [strukturag/nextcloud-spreed-signaling#332] opened 2022-09-12 21:55 UTC
# Enviroment
Two servers, one HPB and other with NC:
- Ubuntu LTS 22.0.4
> - Janus v0.11.8 
> - NATS (docker latest)
> - CoTURN (docker latest)
> - Spreed Signaling version 42a8aab3072cd85ccb3a0bf53513ce78909c8354/go1.18.1
> - Apache for reverse proxy with SSL valid configured

- Debian 11 with docker v20.10.17
> - Nextcloud v24.0.4 docker with SSL valid configured

# Configuration

## signaling.conf
```
[http]
listen = 0.0.0.0:8081

[sessions]
hashkey = 8ab7...
blockkey = d150...

[backend]
backends = backend-1
allowall = true    #false
timeout = 10
connectionsperhost = 8

[backend-1]
url = https://mydomain.tld
secret = $SECRET_BACKEND

[nats]
url = nats://127.0.0.1:4222

[mcu]
type = janus
url = ws://127.0.0.1:8188

[turn]
apikey = $MYSECRET_API
secret = $MYSECRET_TURN
servers = turn:127.0.0.1:5349?transport=tcp,turn:127.0.0.1:5349?transport=udp
```

## NC admin
- HPB Infra with secret and validation SSL ok

# Problems
## In chat talk
- Users  status not available;
- field to write message;
- "start call" blocked;

## Logs signaling
This generates while chat is open:
```
client.go:282: Client from XX.XX.XX.93 has RTT of 43 ms (43.059872ms)
backend_client.go:164: Could not send request {"type":"auth","auth":{"version":"1.0","params":{"userid":"user","ticket":"XM4r9GcI6VPCvYZS:1663017250:user:bb35b4070948f8a5b13b715d781ad72285e2bdd0e420e682363909576ecd68b7"}}} to https://mydomain.tld/ocs/v2.php/apps/spreed/api/v3/signaling/backend: Post "https://mydomain.tld/ocs/v2.php/apps/spreed/api/v3/signaling/backend": context deadline exceeded
```

The one below also occurred at some point:
```
client.go:282: Client from XX.XX.XX.93 has RTT of 27 ms (27.300551ms)
backend_client.go:198: Could not decode OCS response body [] from https://mydomain.tld/ocs/v2.php/apps/spreed/api/v3/signaling/backend: parse error: expected { near offset 1 of ''
```

**Comment by malehovich** [comment] 2022-09-13 12:12
Same problem. Latest versions of conferences and signaling server.

**Comment by willyamcts** [comment] 2022-09-13 14:39
Same problem in stable release 1.0.0 / 33dc5a554b496bd253bedbecc6755de514a64867. This version is used in [nextcloud-all-in-one](https://github.com/nextcloud/all-in-one). 

In nextcloud Infra HPB status:

> "OK: Version running: unknown."

\# nextcloud-spreed-signaling-1.0.0/bin/signaling --version

> nextcloud-spreed-signaling version unknown/go1.18.1

**Comment by willyamcts** [comment] 2022-09-21 12:08
> Same problem. Latest versions of conferences and signaling server.

In commit cbfc96e (release stable 0.5.0) this problem does not happen. If it helps you...

**Comment by iron-udjin** [comment] 2022-10-25 00:11
Have the same problem with 0.5.0. Any progress on this? According to changelog the issue is not fixed in 1.0.0.

**Comment by johannes-hafner** [comment] 2022-10-26 15:43
The issue is caused by Nextcloud returning `{"ocs":{"meta":{"status":"failure","statuscode":400,"message":null},"data":"Internal signaling disabled."}}` to `ocs/v2.php/apps/spreed/api/v3/signaling/capabilities`. the `data` node does not contain an object here, but the signaling server expects one.

I assume the issue is actually caused by Nextcloud not returning its capabilities with external signaling server enabled (however with internal signaling turned on, it returns an 404 on the capabilities endpoint, which seems wrong as well)

(Nextcloud version: 24.0.6, Talk Plugin Version: 14.0.5)

**Comment by johannes-hafner** [comment] 2022-10-26 16:39
Both messages seem to be timeout issues. The json syntax error is caused by an incorrect formatted response from the server in case of a timeout: `{"ocs":{"meta":{"status":"failure","statuscode":429,"message":"Reached maximum delay"},"data":[]}}` - here, the `data` node holds an empty array, while the signaling server expects an object.

**Closed** 2023-01-17 12:44 UTC
